---
type: pipeline
name: Deploy Reeve Documentation

when:
  workerGroup:
    include: [soldier]
  trigger:
    include: [commit, action]
  action:
    include: [reeveci:documentation:deploy]

steps:
  - name: Deploy
    task: "@reeve/npm-cli"
    params:
      SSH_KEY: { env: github/reeve/documentation/ssh-key }
      GIT_USER_NAME: { env: github/reeve/documentation/name }
      GIT_USER_EMAIL: { env: github/reeve/documentation/email }
    command: /bin/sh
    input: |
      set -e

      mkdir -p ~/.ssh
      echo "$SSH_KEY" >~/.ssh/id_github
      echo "IdentityFile ~/.ssh/id_github" >~/.ssh/config
      chmod 0700 ~/.ssh
      chmod 0600 ~/.ssh/config ~/.ssh/id_github
      unset SSH_KEY

      npm run deploy
