---
type: pipeline
name: Deploy Reeve Documentation

when:
  workerGroup:
    include: [soldier]
  trigger:
    include: [commit, action]
  action:
    include: [reeveci:documentation:deploy]

steps:
  - name: Deploy
    task: "@reeve/npm-cli"
    params:
      SSH_KEY: { env: github/reeve/documentation/ssh-key }
      SSH_KNOWN_HOSTS: { env: github/fingerprints }
      GIT_USER_EMAIL: { env: github/reeve/documentation/email }
      GIT_USER_NAME: { env: github/reeve/documentation/name }
    command: /bin/sh
    input: |
      set -e

      mkdir -m 0700 -p ~/.ssh
      echo 'IdentityFile ~/.ssh/id_github' >~/.ssh/config
      echo "$SSH_KEY" >~/.ssh/id_github
      echo "$SSH_KNOWN_HOSTS" >~/.ssh/known_hosts
      chmod 0600 ~/.ssh/config ~/.ssh/id_github ~/.ssh/known_hosts
      unset SSH_KEY SSH_KNOWN_HOSTS

      git config --global user.email "$GIT_USER_EMAIL"
      git config --global user.name "$GIT_USER_NAME"
      git remote add origin git@github.com:reeveci/reeveci.github.io

      npm ci
      npm run deploy
